version: "3" 
services:
  users:
    container_name: users
    build: users/
    image: users:latest
    command: python3 users.py
    ports:
      - "8080:80"
    environment:
      - TEAM_NAME=CC_0190_0218_0872
    links:
      - "user-db:db"
    depends_on:
      - user-db
    restart: always

  user-db:
    image: postgres
    container_name: users_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "33000:5432"
    #command: -p 5432
    expose:
      - "5432"  

  rides:
    container_name: rides
    build: rides/
    image: rides:latest
    command: python3 rides.py
    restart: always
    ports:
      - "8000:80"
    environment:
      - TEAM_NAME=CC_0190_0218_0872
    links:
      - "rides-db:db"
    depends_on:
      - rides-db
  rides-db:
    image: postgres
    container_name: rides_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "32000:5432"
    #command: -p 5432
    expose:
      - "5432"
