version: '3.1'

services:

  zoo:
    image: zookeeper
    container_name: zoo
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
  
  rmq:
    image: rabbitmq:3.8.3-alpine
    container_name: rmq
    ports:
      - 5672:5672
      - 15672:15672

  orchestrator:
    container_name : orchestrator
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 30 && python3 orchestrator_fixed.py"
    volumes:
        - .:/code
        - /var/run/docker.sock:/var/run/docker.sock
    links:
        - rmq
        - zoo
    depends_on:
        - rmq
        - zoo
    restart: on-failure
    ports:
        - 80:5000
  
  worker:
    image: worker:latest
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - rmq
      - zoo
    depends_on:
      - rmq
      - zoo
    restart: on-failure
    
  
