version: '3.1'
services:
  users:
    container_name: users
    build:
      context: .
      dockerfile: Dockerfile
    image: users:latest
    command: python3 users.py
    ports:
      - "80:80"
    environment:
      - TEAM_NAME=CC_0190_0218_0872
    restart: always