version: "3" 
services:
 

  rides:
    container_name: rides
    build: rides/
    image: rides:latest
    command: python3 rides.py
    restart: always
    ports:
      - "80:80"
    environment:
      - TEAM_NAME=CC_0190_0218_0872
    links:
      - "rides-db:db"
    depends_on:
      - rides-db
  rides-db:
    image: postgres
    container_name: rides_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "32000:5432"
    #command: -p 5432
    expose:
      - "5432"
